service: arpnd
keys:
  - ipAddress
  - oif

show-fields:
  - ipAddress
  - oif
  - macaddr
  - state
  - offload

apply:
  cumulus:
    version: all
    command: ip neigh show
    textfsm: textfsm_templates/linux_ipneigh.tfsm

  linux:
    copy: cumulus

  eos:
    version: all
    command: show arp
    normalize: 'ipV4Neighbors/[
    "hwAddress: macaddr",
    "address: ipAddress",
    "interface: oif",
    "state: state?|reachable",
    "offload: offload?|False",
    ]'
