
service: bgp
ignore-fields:
  - lastDownTime
  - estdTime
keys:
  - vrf
  - peer
show-fields:
  - vrf
  - peer
  - peerHostname
  - state
  - asn
  - peerAsn
  - v4PfxRx
  - estdTime
  - numChanges

apply:
  eos:
    version: all
    command: show ip bgp neighbors vrf all
    normalize: 'vrfs/*/peerList/*/[
        "asn: peerAsn?|0", 
        "localAsn: asn?|0", 
        "updateSource: source",
        "peerHostname: peerHostname?|",
        "peerAddress: peer",
        "peerAddress: peerIP?|",
        "vrf: vrf",
        "maintenance: maintenance", 
        "establishFailHint: reason",
        "notificnReason: notificnReason?|",
        "lastErrorTimeInfo/time: lastDownTime?|0",
        "prefixesReceived: v4PfxRx?|0",
        "prefixesSent: v4PfxTx?|0",
        "v6PrefixesReceived: v6PfxRx?|0",
        "v6PrefixesSent: v6PfxTx?|0",
        "receivedUpdates: updatesRx?|0",
        "bgpSoftReconfigInbound: softConfigIn?|",
        "routeMapInfo/outboundIpv4Uni: v4EgressRmap",
        "routeMapInfo/outboundIpv6Uni: v6EgressRmap",
        "routeMapInfo/outboundEvpn: evpnEgressRmap",
        "routeMapInfo/inboundIpv4Uni: v4IngressRmap",
        "routeMapInfo/inboundIpv6Uni: v6IngressRmap",
        "routeMapInfo/inboundEvpn: evpnIngressRmap",
        "sentUpdates: updatesTx?|0",
        "routerId: peerRouterId",
        "localRouterId: routerId",
        "holdTime": "holdTime?|0",
        "keepaliveTime": "keepaliveTime?|0",
        "establishedTime: estdTime?|0",
        "establishedTransitions: numChanges?|0",
        "updateSource: updateSource?|",
        "v4Enabled: v4Enabled?|True",
        "v6Enabled: v6Enabled?|False",
        "evpnEnabled: evpnEnabled?|False",
        "v4Advertised: v4Advertised?|False",
        "v6Advertised: v6Advertised?|False",
        "evpnAdvertised: evpnAdvertised?|False",
        "v4Received: v4Received?|False",
        "v6Received: v6Received?|False",
        "evpnReceived: evpnReceived?|False",
        "bfdState: bfdStatus?|disabled",
        "v6BestEcmpPaths: v6EcmpEnabled?|0",
        "v4BestEcmpPaths: v4EcmpEnabled?|0",
        "state: state?Established|NotEstd"]'
  cumulus:
    version: all
    command: net show bgp vrf all neighbor json
    normalize: '*:vrf/*:peer/[
        "remoteAs: peerAsn",
        "localAs: asn",
        "lastResetDueTo: reason?|",
        "lastNotificationReason: notifcnReason?|",
        "lastResetTimerMsecs: lastDownTime?|0",
        "addressFamilyInfo/IPv4 Unicast/acceptedPrefixCounter: v4PfxRx?|0",
        "addressFamilyInfo/IPv6 Unicast/acceptedPrefixCounter: v6PfxRx?|0",
        "addressFamilyInfo/L2VPN EVPN/acceptedPrefixCounter: evpnPfxRx?|0",
        "addressFamilyInfo/L2VPN EVPN/advertiseAllVnis: advertiseAllVnis?|False",
        "addressFamilyInfo/L2VPN EVPN/commAttriSentToNbr: evpnSendCommunity?|",
        "addressFamilyInfo/L2VPN EVPN/unchangedNextHopPropogatedToNbr: nhUnchanged?|False",
        "addressFamilyInfo/l2vpnEvpn/advertiseAllVnis: advertiseAllVnis?|advertiseAllVnis",
        "addressFamilyInfo/l2vpnEvpn/unchangedNextHopPropogatedToNbr: nhUnchanged?|nhUnchanged",
        "addressFamilyInfo/l2vpnEvpn/commAttriSentToNbr: evpnSendCommunity?|",
        "addressFamilyInfo/ipv4Unicast/acceptedPrefixCounter: v4PfxRx?|v4PfxRx",
        "addressFamilyInfo/ipv6Unicast/acceptedPrefixCounter: v6PfxRx?|v6PfxRx",
        "addressFamilyInfo/l2vpnEvpn/acceptedPrefixCounter: evpnPfxRx?|evpnPfxRx",
        "addressFamilyInfo/ipv4Unicast/sentPrefixCounter: v4PfxTx?|0",
        "addressFamilyInfo/ipv6Unicast/sentPrefixCounter: v6PfxTx?|0",
        "addressFamilyInfo/l2vpnEvpn/sentPrefixCounter: evpnPfxTx?|0",
        "addressFamilyInfo/ipv4Unicast/routeMapForIncomingAdvertisements: v4IngressRmap?|",
        "addressFamilyInfo/ipv4Unicast/routeMapForOutgoingAdvertisements: v4EgressRmap?|",
        "addressFamilyInfo/ipv6Unicast/routeMapForIncomingAdvertisements: v6IngressRmap?|",
        "addressFamilyInfo/ipv6Unicast/routeMapForOutgoingAdvertisements: v6EgressRmap?|",
        "addressFamilyInfo/l2vpnEvpn/routeMapForIncomingAdvertisements: evpnIngressRmap?|",
        "addressFamilyInfo/l2vpnEvpn/routeMapForOutgoingAdvertisements: evpnEgressRmap?|",
        "messageStats/updatesSent: updatesTx",
        "messageStats/updatesRecv: updatesRx",
        "remoteRouterId: peerRouterId",
        "localRouterId: routerId",
        "bgpState: state?Established|NotEstd",
        "bgpTimerUpMsec: estdTime/1000",
        "connectionsEstablished: numChanges",
        "connectionsDropped: numChanges+numChanges",
        "bgpTimerHoldTimeMsecs: holdTime/1000",
        "bgpTimerKeepAliveIntervalMsecs: keepaliveTime/1000",
        "minBtwnAdvertisementRunsTimerMsecs: mrai/1000",
        "peerBfdInfo/status: bfdStatus?|disabled",
        "neighborCapabilities/hostName/rcvHostName: peerHostname?|",
        "neighborCapabilities/multiprotocolExtensions/ipv4Unicast/advertisedAndReceived: v4Enabled?|False",
        "neighborCapabilities/multiprotocolExtensions/l2vpnEvpn/advertisedAndReceived: evpnEnabled?|False",
        "neighborCapabilities/multiprotocolExtensions/ipv6Unicast/advertisedAndReceived: v6Enabled?|False",
        "neighborCapabilities/multiprotocolExtensions/ipv4Unicast/advertised: v4Advertised?|False",
        "neighborCapabilities/multiprotocolExtensions/l2vpnEvpn/advertised: evpnAdvertised?|False",
        "neighborCapabilities/multiprotocolExtensions/ipv6Unicast/advertised: v6Advertised?|False",
        "neighborCapabilities/multiprotocolExtensions/ipv4Unicast/received: v4Received?|False",
        "neighborCapabilities/multiprotocolExtensions/l2vpnEvpn/received: evpnReceived?|False",
        "neighborCapabilities/multiprotocolExtensions/ipv6Unicast/received: v6Received?|False",
        "neighborCapabilities/multiprotocolExtensions/IPv4 Unicast/advertisedAndReceived: v4Enabled?|v4Enabled",
        "neighborCapabilities/multiprotocolExtensions/L2VPN EVPN/advertisedAndReceived: evpnEnabled?|evpnEnabled",
        "neighborCapabilities/multiprotocolExtensions/IPv6 Unicast/advertisedAndReceived: v6Enabled?|v6Enabled",
        "neighborCapabilities/multiprotocolExtensions/IPv4 Unicast/advertised: v4Advertised?|v4Advertised",
        "neighborCapabilities/multiprotocolExtensions/L2VPN EVPN/advertised: evpnAdvertised?|evpnAdvertised",
        "neighborCapabilities/multiprotocolExtensions/IPv6 Unicast/advertised: v6Advertised?|v6Advertised",
        "neighborCapabilities/multiprotocolExtensions/IPv4 Unicast/received: v4Received?|v4Received",
        "neighborCapabilities/multiprotocolExtensions/L2VPN EVPN/received: evpnReceived?|evpnReceived",
        "neighborCapabilities/multiprotocolExtensions/IPv6 Unicast/received: v6Received?|v6Received",
        "hostLocal: updateSource?|",
        "hostForeign: peerIP?|"]'
  linux:
      version: all
      command: sudo vtysh -c "show ip bgp vrf all neighbors json"
      normalize: '*:vrf/*:peer/[
        "remoteAs: peerAsn",
        "localAs: asn",
        "lastResetDueTo: reason?|",
        "lastNotificationReason: notifcnReason?|",
        "lastResetTimerMsecs: lastDownTime?|0",
        "addressFamilyInfo/IPv4 Unicast/acceptedPrefixCounter: v4PfxRx?|0",
        "addressFamilyInfo/IPv6 Unicast/acceptedPrefixCounter: v6PfxRx?|0",
        "addressFamilyInfo/L2VPN EVPN/acceptedPrefixCounter: evpnPfxRx?|0",
        "addressFamilyInfo/L2VPN EVPN/advertiseAllVnis: advertiseAllVnis?|False",
        "addressFamilyInfo/L2VPN EVPN/commAttriSentToNbr: evpnSendCommunity?|",
        "addressFamilyInfo/L2VPN EVPN/unchangedNextHopPropogatedToNbr: nhUnchanged?|False",
        "addressFamilyInfo/l2vpnEvpn/advertiseAllVnis: advertiseAllVnis?|advertiseAllVnis",
        "addressFamilyInfo/l2vpnEvpn/unchangedNextHopPropogatedToNbr: nhUnchanged?|nhUnchanged",
        "addressFamilyInfo/l2vpnEvpn/commAttriSentToNbr: evpnSendCommunity?|",
        "addressFamilyInfo/ipv4Unicast/acceptedPrefixCounter: v4PfxRx?|v4PfxRx",
        "addressFamilyInfo/ipv6Unicast/acceptedPrefixCounter: v6PfxRx?|v6PfxRx",
        "addressFamilyInfo/l2vpnEvpn/acceptedPrefixCounter: evpnPfxRx?|evpnPfxRx",
        "addressFamilyInfo/ipv4Unicast/sentPrefixCounter: v4PfxTx?|0",
        "addressFamilyInfo/ipv6Unicast/sentPrefixCounter: v6PfxTx?|0",
        "addressFamilyInfo/l2vpnEvpn/sentPrefixCounter: evpnPfxTx?|0",
        "addressFamilyInfo/ipv4Unicast/routeMapForIncomingAdvertisements: v4IngressRmap?|",
        "addressFamilyInfo/ipv4Unicast/routeMapForOutgoingAdvertisements: v4EgressRmap?|",
        "addressFamilyInfo/ipv6Unicast/routeMapForIncomingAdvertisements: v6IngressRmap?|",
        "addressFamilyInfo/ipv6Unicast/routeMapForOutgoingAdvertisements: v6EgressRmap?|",
        "addressFamilyInfo/l2vpnEvpn/routeMapForIncomingAdvertisements: evpnIngressRmap?|",
        "addressFamilyInfo/l2vpnEvpn/routeMapForOutgoingAdvertisements: evpnEgressRmap?|",
        "messageStats/updatesSent: updatesTx",
        "messageStats/updatesRecv: updatesRx",
        "remoteRouterId: peerRouterId",
        "localRouterId: routerId",
        "bgpState: state?Established|NotEstd",
        "bgpTimerUpMsec: estdTime/1000",
        "connectionsEstablished: numChanges",
        "connectionsDropped: numChanges+numChanges",
        "bgpTimerHoldTimeMsecs: holdTime/1000",
        "bgpTimerKeepAliveIntervalMsecs: keepaliveTime/1000",
        "minBtwnAdvertisementRunsTimerMsecs: mrai/1000",
        "peerBfdInfo/status: bfdStatus?|disabled",
        "neighborCapabilities/hostName/rcvHostName: peerHostname?|",
        "neighborCapabilities/multiprotocolExtensions/ipv4Unicast/advertisedAndReceived: v4Enabled?|False",
        "neighborCapabilities/multiprotocolExtensions/l2vpnEvpn/advertisedAndReceived: evpnEnabled?|False",
        "neighborCapabilities/multiprotocolExtensions/ipv6Unicast/advertisedAndReceived: v6Enabled?|False",
        "neighborCapabilities/multiprotocolExtensions/ipv4Unicast/advertised: v4Advertised?|False",
        "neighborCapabilities/multiprotocolExtensions/l2vpnEvpn/advertised: evpnAdvertised?|False",
        "neighborCapabilities/multiprotocolExtensions/ipv6Unicast/advertised: v6Advertised?|False",
        "neighborCapabilities/multiprotocolExtensions/ipv4Unicast/received: v4Received?|False",
        "neighborCapabilities/multiprotocolExtensions/l2vpnEvpn/received: evpnReceived?|False",
        "neighborCapabilities/multiprotocolExtensions/ipv6Unicast/received: v6Received?|False",
        "neighborCapabilities/multiprotocolExtensions/IPv4 Unicast/advertisedAndReceived: v4Enabled?|v4Enabled",
        "neighborCapabilities/multiprotocolExtensions/L2VPN EVPN/advertisedAndReceived: evpnEnabled?|evpnEnabled",
        "neighborCapabilities/multiprotocolExtensions/IPv6 Unicast/advertisedAndReceived: v6Enabled?|v6Enabled",
        "neighborCapabilities/multiprotocolExtensions/IPv4 Unicast/advertised: v4Advertised?|v4Advertised",
        "neighborCapabilities/multiprotocolExtensions/L2VPN EVPN/advertised: evpnAdvertised?|evpnAdvertised",
        "neighborCapabilities/multiprotocolExtensions/IPv6 Unicast/advertised: v6Advertised?|v6Advertised",
        "neighborCapabilities/multiprotocolExtensions/IPv4 Unicast/received: v4Received?|v4Received",
        "neighborCapabilities/multiprotocolExtensions/L2VPN EVPN/received: evpnReceived?|evpnReceived",
        "neighborCapabilities/multiprotocolExtensions/IPv6 Unicast/received: v6Received?|v6Received",
        "hostLocal: updateSource?|",
        "hostForeign: peerIP?|"]'


