
service: bgp
ignore-fields:
  - lastDownTime
  - estdTime
keys:
  - vrf
  - peer
show-fields:
  - vrf
  - peer
  - state
  - asn
  - peerAsn
  - v4PfxRx
  - estdTime
  - transitionCnt
apply:
  eos:
    version: all
    command: show ip bgp neighbors
    normalize: 'vrfs/*/peerList/*/[
        "asn: peerAsn", 
        "localAsn: asn", 
        "updateSource: source",
        "peerAddress: peer", 
        "vrf: vrf", 
        "maintenance: maintenance", 
        "establishFailHint: reason",
        "lastErrorTimeInfo/time: lastDownTime?|0",
        "prefixesReceived: v4PfxRx",
        "prefixesSent: v4PfxTx",
        "v6PrefixesReceived: v6PfxRx",
        "v6PrefixesSent: v6PfxTx",
        "receivedUpdates: updatesRx",
        "sentUpdates: updatesTx",
        "routerId: peerRouterId",
        "localRouterId: routerId",
        "establishedTime: estdTime?|0.0",
        "establishedTransitions: transitionCnt",
        "v4Enabled: v4Enabled?|True",
        "v6Enabled: v6Enabled?|False",
        "evpnEnabled: evpnEnabled?|False",
        "state: state?Established|NotEstd"]'
  cumulus:
      version: all
      command: net show bgp vrf all neighbor json
      normalize: '*:vrf/*:peer/[
        "remoteAs: peerAsn",
        "localAs: asn",
        "hostLocal: source",
        "lastResetDueTo: reason",
        "lastResetTimerMsecs: lastDownTime?|0",
        "addressFamilyInfo/IPv4 Unicast/acceptedPrefixCounter: v4PfxRx",
        "addressFamilyInfo/IPv6 Unicast/acceptedPrefixCounter: v6PfxRx?|0",
        "addressFamilyInfo/L2VPN EVPN/acceptedPrefixCounter: evpnPfxRx?|0",
        "messageStats/updatesSent: updatesTx",
        "messageStats/updatesRecv: updatesRx",
        "remoteRouterId: peerRouterId",
        "bgpState: state?Established|NotEstd",
        "bgpTimerUpMsec: div(estdTime,1000)",
        "connectionsEstablished: transitionCnt",
        "connectionsDropped: add(transitionCnt,transitionCnt)",
        "hostname: peerHostname",
        "neighborCapabilities/multiprotocolExtensions/IPv4 Unicast/advertisedAndReceived: v4Enabled?|False",
        "neighborCapabilities/multiprotocolExtensions/L2VPN EVPN/advertisedAndReceived: evpnEnabled?|False",
        "neighborCapabilities/multiprotocolExtensions/IPv6 Unicast/advertisedAndReceived: v6Enabled?|False"]'
