
service: bgp
ignore-fields:
  - lastDownTime
  - estdTime
keys:
  - vrf
  - peer
show-fields:
  - vrf
  - peer
  - state
  - asn
  - peerAsn
  - v4PfxRx
  - estdTime
  - numChanges
apply:
  eos:
    version: all
    command: show ip bgp neighbors vrf all
    normalize: 'vrfs/*/peerList/*/[
        "asn: peerAsn", 
        "localAsn: asn", 
        "updateSource: source",
        "peerAddress: peer", 
        "vrf: vrf", 
        "maintenance: maintenance", 
        "establishFailHint: reason",
        "lastErrorTimeInfo/time: lastDownTime?|0",
        "prefixesReceived: v4PfxRx?|0",
        "prefixesSent: v4PfxTx?|0",
        "v6PrefixesReceived: v6PfxRx?|0",
        "v6PrefixesSent: v6PfxTx?|0",
        "receivedUpdates: updatesRx?|0",
        "routeMapInfo/outboundIpv4Uni: v4EgressRmap",
        "routeMapInfo/outboundIpv6Uni: v6EgressRmap",
        "routeMapInfo/outboundEvpn: evpnEgressRmap",
        "routeMapInfo/inboundIpv4Uni: v4IngressRmap",
        "routeMapInfo/inboundIpv6Uni: v6IngressRmap",
        "routeMapInfo/inboundEvpn: evpnIngressRmap",
        "sentUpdates: updatesTx?|0",
        "routerId: peerRouterId",
        "localRouterId: routerId",
        "holdTime": "holdTime?|0",
        "keepaliveTime": "keepaliveTime?|0",
        "establishedTime: estdTime?|0",
        "establishedTransitions: numChanges?|0",
        "v4Enabled: v4Enabled?|True",
        "v6Enabled: v6Enabled?|False",
        "evpnEnabled: evpnEnabled?|False",
        "bfdState: bfdStatus?|disabled",
        "v6BestEcmpPaths: v6EcmpEnabled?|0",
        "v4BestEcmpPaths: v4EcmpEnabled?|0",
        "state: state?Established|NotEstd"]'

  cumulus:
    version: all
    command: net show bgp vrf all neighbor json
    normalize: '*:vrf/*:peer/[
        "remoteAs: peerAsn",
        "localAs: asn",
        "hostLocal: source",
        "lastResetDueTo: reason",
        "lastResetTimerMsecs: lastDownTime?|0",
        "addressFamilyInfo/IPv4 Unicast/acceptedPrefixCounter: v4PfxRx?|0",
        "addressFamilyInfo/IPv6 Unicast/acceptedPrefixCounter: v6PfxRx?|0",
        "addressFamilyInfo/L2VPN EVPN/acceptedPrefixCounter: evpnPfxRx?|0",
        "addressFamilyInfo/ipv4Unicast/acceptedPrefixCounter: newv4PfxRx?|0",
        "addressFamilyInfo/ipv6Unicast/acceptedPrefixCounter: newv6PfxRx?|0",
        "addressFamilyInfo/l2vpnEvpn/acceptedPrefixCounter: newevpnPfxRx?|0",
        "addressFamilyInfo/ipv4Unicast/sentPrefixCounter: v4PfxTx?|0",
        "addressFamilyInfo/ipv6Unicast/sentPrefixCounter: v6PfxTx?|0",
        "addressFamilyInfo/l2vpnEvpn/sentPrefixCounter: evpnPfxTx?|0",
        "addressFamilyInfo/ipv4Unicast/routeMapForIncomingAdvertisements: v4IngressRmap?|",
        "addressFamilyInfo/ipv4Unicast/routeMapForOutgoingAdvertisements: v4EgressRmap?|",
        "addressFamilyInfo/ipv6Unicast/routeMapForIncomingAdvertisements: v6IngressRmap?|",
        "addressFamilyInfo/ipv6Unicast/routeMapForOutgoingAdvertisements: v6EgressRmap?|",
        "addressFamilyInfo/l2vpnEvpn/routeMapForIncomingAdvertisements: evpnIngressRmap?|",
        "addressFamilyInfo/l2vpnEvpn/routeMapForOutgoingAdvertisements: evpnEgressRmap?|",
        "messageStats/updatesSent: updatesTx",
        "messageStats/updatesRecv: updatesRx",
        "remoteRouterId: peerRouterId",
        "localRouterId: routerId",
        "bgpState: state?Established|NotEstd",
        "bgpTimerUpMsec: estdTime/1000",
        "connectionsEstablished: numChanges",
        "connectionsDropped: numChanges+numChanges",
        "bgpTimerHoldTimeMsecs: holdTime/1000",
        "bgpTimerKeepAliveIntervalMsecs: keepaliveTime/1000",
        "minBtwnAdvertisementRunsTimerMsecs: mrai/1000",
        "hostName/rcvHostName: peerHostname",
        "peerBfdInfo/status: bfdStatus?|disabled",
        "neighborCapabilities/multiprotocolExtensions/ipv4Unicast/advertisedAndReceived: newv4Enabled?|False",
        "neighborCapabilities/multiprotocolExtensions/l2vpnEvpn/advertisedAndReceived: newevpnEnabled?|False",
        "neighborCapabilities/multiprotocolExtensions/ipv6Unicast/advertisedAndReceived: newv6Enabled?|False",
        "neighborCapabilities/multiprotocolExtensions/IPv4 Unicast/advertisedAndReceived: v4Enabled?|False",
        "neighborCapabilities/multiprotocolExtensions/L2VPN EVPN/advertisedAndReceived: evpnEnabled?|False",
        "neighborCapabilities/multiprotocolExtensions/IPv6 Unicast/advertisedAndReceived: v6Enabled?|False"]'

  linux:
      version: all
      command: sudo vtysh -c "show ip bgp vrf all neighbors json"
      normalize: '*:vrf/*:peer/[
        "remoteAs: peerAsn",
        "localAs: asn",
        "hostLocal: source",
        "lastResetDueTo: reason",
        "lastResetTimerMsecs: lastDownTime?|0",
        "addressFamilyInfo/IPv4 Unicast/acceptedPrefixCounter: v4PfxRx?|0",
        "addressFamilyInfo/IPv6 Unicast/acceptedPrefixCounter: v6PfxRx?|0",
        "addressFamilyInfo/L2VPN EVPN/acceptedPrefixCounter: evpnPfxRx?|0",
        "addressFamilyInfo/ipv4Unicast/acceptedPrefixCounter: newv4PfxRx?|0",
        "addressFamilyInfo/ipv6Unicast/acceptedPrefixCounter: newv6PfxRx?|0",
        "addressFamilyInfo/l2vpnEvpn/acceptedPrefixCounter: newevpnPfxRx?|0",
        "addressFamilyInfo/ipv4Unicast/sentPrefixCounter: v4PfxTx?|0",
        "addressFamilyInfo/ipv6Unicast/sentPrefixCounter: v6PfxTx?|0",
        "addressFamilyInfo/l2vpnEvpn/sentPrefixCounter: evpnPfxTx?|0",
        "addressFamilyInfo/ipv4Unicast/routeMapForIncomingAdvertisements: v4IngressRmap?|",
        "addressFamilyInfo/ipv4Unicast/routeMapForOutgoingAdvertisements: v4EgressRmap?|",
        "addressFamilyInfo/ipv6Unicast/routeMapForIncomingAdvertisements: v6IngressRmap?|",
        "addressFamilyInfo/ipv6Unicast/routeMapForOutgoingAdvertisements: v6EgressRmap?|",
        "addressFamilyInfo/l2vpnEvpn/routeMapForIncomingAdvertisements: evpnIngressRmap?|",
        "addressFamilyInfo/l2vpnEvpn/routeMapForOutgoingAdvertisements: evpnEgressRmap?|",
        "messageStats/updatesSent: updatesTx",
        "messageStats/updatesRecv: updatesRx",
        "remoteRouterId: peerRouterId",
        "localRouterId: routerId",
        "bgpState: state?Established|NotEstd",
        "bgpTimerUpMsec: estdTime/1000",
        "connectionsEstablished: numChanges",
        "connectionsDropped: numChanges+numChanges",
        "bgpTimerHoldTimeMsecs: holdTime/1000",
        "bgpTimerKeepAliveIntervalMsecs: keepaliveTime/1000",
        "minBtwnAdvertisementRunsTimerMsecs: mrai/1000",
        "hostName/rcvHostName: peerHostname",
        "peerBfdInfo/status: bfdStatus?|disabled",
        "neighborCapabilities/multiprotocolExtensions/ipv4Unicast/advertisedAndReceived: newv4Enabled?|False",
        "neighborCapabilities/multiprotocolExtensions/l2vpnEvpn/advertisedAndReceived: newevpnEnabled?|False",
        "neighborCapabilities/multiprotocolExtensions/ipv6Unicast/advertisedAndReceived: newv6Enabled?|False",
        "neighborCapabilities/multiprotocolExtensions/IPv4 Unicast/advertisedAndReceived: v4Enabled?|False",
        "neighborCapabilities/multiprotocolExtensions/L2VPN EVPN/advertisedAndReceived: evpnEnabled?|False",
        "neighborCapabilities/multiprotocolExtensions/IPv6 Unicast/advertisedAndReceived: v6Enabled?|False"]'

