service: device
show-fields:
  - model
  - version
  - vendor
  - architecture
  - status
  - address
  - bootupTimestamp
apply:
  eos:
    version: all
    command: show version
    normalize: '[
    "modelName: model",
    "version: version",
    "vendor: vendor?|Arista",
    "os: os?|EOS",
    "architecture: architecture",
    "bootupTimestamp: bootupTimestamp"]'

  cumulus:
    version: all
    command: cat /proc/uptime; hostnamectl
    textfsm: textfsm_templates/cl_showsys.tfsm

  linux:
    version: all
    command: cat /proc/uptime; hostnamectl
    textfsm: textfsm_templates/linux_showsys.tfsm

  platina:
    copy: linux
  
