service: evpnVni
keys:
  - vni

show-fields:
  - vni
  - type
  - numMacs
  - numArpNd
  - remoteVtepList

apply:
  cumulus:
    version: all
    command: sudo vtysh -c "show evpn vni detail json"
    normalize: '*/[
    "vni: vni",
    "type: type",
    "numMacs: numMacs?|0",
    "numArpNd: numArpNd?|0",
    "numRemoteVteps: remoteVtepList?|[]",
    "l2Vnis: l2VniList?|[]",
    "advertiseGatewayMacIp: advGateway?|False",
    "vtepIp: srcVtepIp?|",
    "localVtepIp: srcVtepIp?|srcVtepIp",
    "vniFilter: vniFilter?|",
    "state: state?|up",
    "vxlanInterface: ifname?|",
    "routerMac: routerMac?|",
    "vrf: vrf",
    ]'

  linux:
    copy: cumulus

