service: ifCounters
type: counters
keys:
  - ifname
apply:
  cumulus:
    version: all
    command: cat /proc/net/dev
    textfsm: /home/ddutt/work/suzieq/config/textfsm_templates/ifCounters.tfsm

  eos:
    version: all
    command: show interfaces
    normalize: 'interfaces/*/[
    "name: ifname",
    "interfaceCounters/inOctets: rxBytes?|0",
    "interfaceCounters/inTotalPkts: rxPackets?|0",
    "interfaceCounters/inDiscards: rxDrops?|0",
    "interfaceCounters/totalInErrors: rxErrs?|0",
    "interfaceCounters/outOctets: txBytes?|0",
    "interfaceCounters/outUcastPkts: txPackets?|0",
    "interfaceCounters/outMulticastPkts: txPackets + txPackets",
    "interfaceCounters/outBroadcastPkts: txPackets + txPackets",
    "interfaceCounters/totalOutErrors: txErrs?|0",
    "interfaceCounters/outDiscards: txDrops?|0"
    ]'
    
