service: interfaces
keys:
  - ifname

show-fields:
  - ifname
  - state
  - type
  - mtu
  - master

apply:
  cumulus:
    copy: linux

  eos:
    version: all
    command: show interfaces
    normalize: 'interfaces/*/[
    "name: ifname",
    "mtu: mtu",
    "description: description",
    "physicalAddress: macaddr",
    "bandwidth: speed",
    "lineProtocolStatus: state",
    "hardware: type",
    "fallbackEnabled: lacpBypass?|False",
    "interfaceMembership: master",
    "interfaceAddress: ipAddressList?|[]",
    "interfaceAddressIP6: ip6AddressList?|[]",
    ]'

  linux:
    version: all
    command: ip -d address show
    textfsm: textfsm_templates/linux_ipaddr.tfsm

  platina:
    copy: linux
  
