service: interfaces
keys:
  - ifname

show-fields:
  - ifname
  - state
  - type
  - mtu
  - master
  - ipAddressList
  - ip6AddressList

apply:
  cumulus:
    version: all
    command: sudo vtysh -c "show int vrf all"; ip -d address show
    textfsm: textfsm_templates/cl_interfaces.tfsm

  eos:
    version: all
    command: show interfaces
    # bunch of fields need code fixups. see service file
    normalize: 'interfaces/*/[
    "name: ifname",
    "mtu: mtu?|0",
    "description: description",
    "physicalAddress: macaddr",
    "bandwidth: speed?|0",
    "srcIpAddr: srcVtepIp",
    "vlanToVniMap/*:vlan?|0",
    "vlanToVniMap/*/vni: vni?|0",
    "lineProtocolStatus: state",
    "hardware: type",
    "forwardingModel: forwardingModel",
    "linkStatusChanges: numChanges?|0",
    "lastStatusChangeTimeStamp: statusChangeTimestamp",
    "fallbackEnabled: lacpBypass?|False",
    "interfaceMembership: master",
    "interfaceAddress: ipAddressList?|[]",
    "interfaceAddressIP6: ip6AddressList?|[]",
    ]'

  linux:
    version: all
    command: ip -d address show
    textfsm: textfsm_templates/linux_ipaddr.tfsm

  platina:
    copy: cumulus
  
