service: lldp
keys:
  - ifname
apply:
  cumulus:
    version: all
    command: net show lldp json
    normalize: 'lldp/[0]/interface/*/[
    "name: ifname",
    "chassis/[0]/name/[0]/value: peerHostname",
    "chassis/[0]/descr/[0]/value: description",
    "chassis/[0]/mgmt-ip/[0]/value: mgmtIP",
    "port/[0]/id/[0]/value: peerIfname"]'

  eos:
    version: all
    command: show lldp neighbors
    normalize: 'lldpNeighbors/*/[
    "port: ifname",
    "neighborDevice: peerHostname",
    "description: description?|-",
    "mgmtIP: mgmtIP?|-",
    "neighborPort: peerIfname"]'

