service: macs
keys:
  # We deliberately don't have VLAN as a key field. We add an artificial
  # key field in the schema and during data cleanup to handle EVPN HER
  # entries among other cases where the VLAN doesn't disambiguate MAC addr.
  - macaddr

show-fields:
  - vlan
  - macaddr
  - oif
  - remoteVtepIp
  - flags

apply:
  cumulus:
    version: all
    command: /sbin/bridge fdb show
    textfsm: textfsm_templates/linux_fdb.tfsm

  linux:
    copy: cumulus

  platina:
    copy: cumulus
  
