service: memory
type: counters
apply:
  cumulus:
    version: all
    command: cat /proc/meminfo; sudo vtysh -c "show memory"
    textfsm: textfsm_templates/cl_meminfo.tfsm

  linux:
    version: all
    command: cat /proc/meminfo
    textfsm: textfsm_templates/linux_meminfo.tfsm

  eos:
    version: all
    command: bash cat /proc/meminfo
    format: text
    textfsm: textfsm_templates/linux_meminfo.tfsm
    
