
service: ospfIf
ignore-fields:
keys:
  - vrf
  - ifname
show-fields:
  - vrf
  - ifname
  - area
  - state
  - passive
  - nbrCount
apply:
  eos:
    version: all
    command: show ip ospf interface
    normalize: 'vrfs/*:vrf/instList/*:instance/interfaces/*:ifname/[
       "passive: passive?|False",
       "helloInterval: helloTime?|0",
       "area: area?|",
       "retransmitInterval: retxTime?|0",
       "interfaceType: networkType?|",
       "deadInterval: deadTime?|0",
       "neighborCount: nbrCount?|0",
       "state: state?|",
       "interfaceAddress: ipAddress?|",
       "cost: cost?|0",
       "routerId: routerId?|",
       "isUnnumbered: False",
       "interfaceMask: maskLen?|32",
       ]'

  cumulus:
    version: all
    command: sudo vtysh -c 'show ip ospf interface'
    textfsm: textfsm_templates/frr_ospfif.tfsm

  platina:
    copy: cumulus

  linux:
    copy: cumulus


