
service: ospfIf
ignore-fields:
keys:
  - vrf
  - ifname
show-fields:
  - vrf
  - ifname
  - area
  - state
  - passive
  - nbrCount
apply:
  eos:
    version: all
    command: show ip ospf interface
    normalize: 'vrfs/*:vrf/instList/*:instance/interfaces/*:ifname/[
       "passive: passive?|False",
       "helloInterval: helloTime?|0",
       "area: area?|",
       "retransmitInterval: retxTime?|0",
       "interfaceType: networkType?|",
       "deadInterval: deadTime?|0",
       "neighborCount: nbrCount?|0",
       "state: state?|",
       "interfaceAddress: ipAddress?|",
       "cost: cost?|0",
       "routerId: routerId?|",
       "isUnnumbered: False",
       "interfaceMask: maskLen?|32",
       ]'

  cumulus:
    version: all
    command: sudo vtysh -c 'show ip ospf interface'
    textfsm: textfsm_templates/frr_ospfif.tfsm

  linux:
    copy: cumulus

  junos:
    version: all
    command: show ospf interface detail | display json
    normalize: 'ospf-interface-information/[0]/ospf-interface/*/[
    "interface-name/[0]/data: ifname",
    "interface-name/[0]/data: origIfname",
    "ospf-interface-state/[0]/data: state",
    "ospf-area/[0]/data: area",
    "neighbor-count/[0]/data: nbrCount?|0",
    "interface-type/[0]/data: networkType?|",
    "interface-address/[0]/data: ipAddress",
    "address-mask/[0]/data: maskLen?|32",
    "interface-cost/[0]/data: cost?|0",
    "passive/[0]/data: passive?Passive|False",
    "hello-interval/[0]/data: helloTime?|0",
    "dead-interval/[0]/data: deadTime?|0",
    "retransmit-interval/[0]/data: retxTime?|0",
    "ospf-stub-type/[0]/data: stub",
    ]'

