service: routes
keys:
  - vrf

show-fields:
  - vrf
  - prefix
  - nexthop
  - protocol
  - source
  - metric

apply:
  cumulus:
    version: all
    command: ip route show table all
    textfsm: textfsm_templates/linux_routes.tfsm

  linux:
    copy: cumulus

  platina:
    copy: cumulus

  eos:
    version: all
    command: show ip route vrf all
    normalize: 'vrfs/*:vrf/routes/*:prefix/[
        "routeType: protocol",
        "metric: metric?|0",
        "vias/*/nexthopAddr: list(nexthopIps)",
        "vias/*/interface": list(oifs)"]'
  
