service: routes
keys:
  - vrf
  - prefix

show-fields:
  - vrf
  - prefix
  - nexthopIps
  - oifs
  - protocol
  - source
  - metric
  - ipvers
  - action

apply:
  cumulus:
    version: all
    command: ip route show table all
    textfsm: textfsm_templates/linux_routes.tfsm

  linux:
    copy: cumulus

  eos:
    version: all
    command: show ip route vrf all
    normalize: 'vrfs/*:vrf/routes/*:prefix/[
        "routeType: protocol",
        "metric: metric?|0",
        "routeAction": "action?|forward",
        "hardwareProgrammed: inHardware?|False",
        "vias/*/nexthopAddr: nexthopIps",
        "vias/*/interface": oifs"]'
  
  junos:
    version: all
    command: show route | display json
    normalize: 'route-information/[0]/route-table/*:table-name:vrf/rt/*/[
    "rt-destination/[0]/data: prefix",
    "rt-entry/[0]/protocol-name/[0]/data: protocol",
    "rt-entry/[0]/preference/[0]/data: metric?|0",
    "rt-entry/[0]/active-tag/[0]/data: activeTag",
    "rt-entry/[0]/as-path/[0]/data: asPath?|",
    "rt-entry/[0]/validation-state/[0]/data: validState?|",
    "rt-entry/[0]/nh/[*]/to/[0]/data: nexthopIps",
    "rt-entry/[0]/nh/[*]/via/[0]/data: oifs",
    "rt-entry/[0]/nh/[0]/nh-local-interface/[0]/data: localif?|",
    "rt-entry/[0]/nh-type/[0]/data: action?|forward",
    ]'
