service: routes
keys:
  - vrf
  - prefix

show-fields:
  - vrf
  - prefix
  - nexthopIps
  - oifs
  - protocol
  - source
  - metric
  - ipvers

apply:
  cumulus:
    version: all
    command: ip route show table all
    textfsm: textfsm_templates/linux_routes.tfsm

  linux:
    copy: cumulus

  platina:
    copy: cumulus

  eos:
    version: all
    command: show ip route vrf all
    normalize: 'vrfs/*:vrf/routes/*:prefix/[
        "routeType: protocol",
        "metric: metric?|0",
        "routeAction": "action?|forward",
        "hardwareProgrammed: inHardware?|False",
        "vias/*/nexthopAddr: nexthopIps",
        "vias/*/interface": oifs"]'
  
