service: system
show-fields:
  - model
  - version
  - vendor
  - architecture
  - status
  - bootupTimestamp
apply:
  eos:
    version: all
    command: show version
    normalize: '[
    "modelName: model",
    "version: version",
    "vendor: vendor?|Arista",
    "os: os?|EOS",
    "architecture: architecture",
    "bootupTimestamp: bootupTimestamp"]'

  cumulus:
    version: all
    command: net show system json
    normalize: '[
    "platform/model: model",
    "platform/vendor: vendor",
    "os-version: version",
    "architecture: architecture?|x86-64",
    "uptime: bootupTimestamp"]'

  linux:
    version: all
    command: cat /proc/uptime; hostnamectl
    textfsm: textfsm_templates/linux_showsys.tfsm

  platina:
    copy: linux
  
