service: system
show-fields:
  - model
  - version
  - vendor
  - os
  - bootupTimestamp
apply:
  eos:
    version: all
    command: show version
    normalize: '[
    "modelName: model",
    "version: version",
    "vendor: vendor?|Arista",
    "os: os?|EOS",
    "bootupTimestamp: bootupTimestamp"]'

  cumulus:
    version: all
    command: cat /proc/uptime; net show system
    textfsm: textfsm_templates/cl_showsys.tfsm

  linux:
    version: all
    command: cat /proc/uptime; cat /etc/os-release
    textfsm: textfsm_templates/linux_showsys.tfsm

  platina:
    copy: linux
  
