service: time
apply:
  cumulus:
    version: all
    command: timedatectl
    textfsm: /home/ddutt/work/suzieq/config/textfsm_templates/timedatectl.tfsm

  linux:
    version: all
    command: timedatectl
    textfsm: /home/ddutt/work/suzieq/config/textfsm_templates/timedatectl.tfsm

  eos:
    version: all
    command: show clock
    format: text
    textfsm: /home/ddutt/work/suzieq/config/textfsm_templates/eos_showclock.tfsm
    
