service: time
show-fields:
  - ntpEnabled
  - timezone
  - ntpSync
apply:
  cumulus:
    version: all
    command: timedatectl
    textfsm: textfsm_templates/timedatectl.tfsm

  linux:
    version: all
    command: timedatectl
    textfsm: textfsm_templates/timedatectl.tfsm

  eos:
    version: all
    command: show clock
    format: text
    textfsm: textfsm_templates/eos_showclock.tfsm
    
