service: topcpu
type: counters
apply:
  cumulus:
    version: all
    command: ps -eo pid,ppid,cmd,%mem,%cpu --sort=-%cpu | head -11
    textfsm: textfsm_templates/linux_topproc.tfsm

  linux:
    version: all
    command: ps -eo pid,ppid,cmd,%mem,%cpu --sort=-%cpu | head -11
    textfsm: textfsm_templates/linux_topproc.tfsm

  eos:
    version: all
    command: bash timeout 3 ps -eo pid,ppid,cmd,%mem,%cpu --sort=-%cpu | head -11
    format: text
    textfsm: textfsm_templates/linux_topproc.tfsm
    
