service: topmem
period: 60
type: counters
apply:
  cumulus:
    version: all
    command: top -bn 1 -o '%MEM' | head -17
    textfsm: textfsm_templates/cl_top.tfsm

  linux:
    version: all
    command: top -bn 1 '%MEM' | head -17
    textfsm: textfsm_templates/linux_top.tfsm

  eos:
    version: all
    command: bash timeout 4 top -bn 1 -N | head -17
    format: text
    textfsm: textfsm_templates/cl_top.tfsm
    
