service: vlan
keys:
  - ifname

show-fields:
  - ifname
  - vlan
  - pvid

apply:
  cumulus:
    version: all
    command: /sbin/bridge -c vlan show
    textfsm: textfsm_templates/linux_vlan.tfsm

  linux:
    copy: cumulus

  eos:
    version: all
    command: show interfaces vlans
    format: text
    textfsm: textfsm_templates/eos_vlan.tfsm
