name: integration-tests
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
      - 0.16.0
  pull_request:
    branches:
      - main
      - 0.16.0
  # Also trigger on page_build, as well as release created events
  page_build:
  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install poetry
      run: |
        pip install --upgrade pip
        pip install poetry
    - name: Install dependencies
      run: |
        poetry install -v
        cp build/suzieq-cfg-travis.yml suzieq-cfg.yml
    - name: pytest
      run: |
        poetry run pytest